maxPronounSize: 16

# Whenever you are able to format a string you can use any MiniMessage you want (https://webui.advntr.dev/).
display:
  tab:
    enabled: false
    # The format for the tab list. <pronouns> will be replaced with the player's pronouns, and <player> will be replaced with their name.
    # Requires ProtocolLib to be installed.
    format: '<grey>[<pronouns>]<white> <player>'
  name:
    enabled: true
    # The format for the player's name. <pronouns> will be replaced with the player's pronouns, and <player> will be replaced with their name.
    format: '<grey> <pronouns>'
  chat:
    enabled: true
    # Replaces the name in chat messages (assumes chat messages follow the format <player>: <message>). <pronouns> will be replaced with the player's pronouns, and <player> will be replaced with their name.
    format: "<hover:show_text:'<pronouns>'><player></hover>"